;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Damage.Elements",NewTagName="Damage.Elemental")
+GameplayTagRedirects=(OldTagName="Damage.Elemental.Eletrical",NewTagName="Damage.Elemental.Electrical")
+GameplayTagRedirects=(OldTagName="Reasource.ConductiveEssence",NewTagName="Reasource.ConductiveShreads")
+GameplayTagRedirects=(OldTagName="Item.Module.Wings.rIGHT",NewTagName="Item.Module.Wings.R")
+GameplayTagRedirects=(OldTagName="Item.Module.Wings.LEft",NewTagName="Item.Module.Wings.L")
+GameplayTagList=(Tag="Damage",DevComment="")
+GameplayTagList=(Tag="Damage.Buffs",DevComment="")
+GameplayTagList=(Tag="Damage.Buffs.Explosive",DevComment="")
+GameplayTagList=(Tag="Damage.Buffs.Penetrating",DevComment="")
+GameplayTagList=(Tag="Damage.Elemental",DevComment="")
+GameplayTagList=(Tag="Damage.Elemental.Corrosive",DevComment="")
+GameplayTagList=(Tag="Damage.Elemental.Electrical",DevComment="")
+GameplayTagList=(Tag="Damage.Elemental.Fire",DevComment="")
+GameplayTagList=(Tag="Enemy",DevComment="")
+GameplayTagList=(Tag="HealthLayers",DevComment="The Layers of damage resistances enemies can have to weapons and damage types")
+GameplayTagList=(Tag="HealthLayers.Armour",DevComment="")
+GameplayTagList=(Tag="HealthLayers.HullBase",DevComment="")
+GameplayTagList=(Tag="HealthLayers.Shield",DevComment="")
+GameplayTagList=(Tag="Item",DevComment="The Source of All Item Derivitives")
+GameplayTagList=(Tag="Item.Module",DevComment="")
+GameplayTagList=(Tag="Item.Module.Cargo",DevComment="")
+GameplayTagList=(Tag="Item.Module.Nose",DevComment="")
+GameplayTagList=(Tag="Item.Module.VTOL",DevComment="")
+GameplayTagList=(Tag="Item.Module.VTOL.L",DevComment="")
+GameplayTagList=(Tag="Item.Module.VTOL.R",DevComment="")
+GameplayTagList=(Tag="Item.Module.Wings",DevComment="")
+GameplayTagList=(Tag="Item.Module.Wings.L",DevComment="")
+GameplayTagList=(Tag="Item.Module.Wings.R",DevComment="")
+GameplayTagList=(Tag="Item.Part",DevComment="Crafting Parts")
+GameplayTagList=(Tag="Item.Reasource",DevComment="")
+GameplayTagList=(Tag="Item.Reasource.1",DevComment="")
+GameplayTagList=(Tag="Item.Reasource.2",DevComment="")
+GameplayTagList=(Tag="Item.Reasource.3",DevComment="")
+GameplayTagList=(Tag="Item.Untagged",DevComment="")
+GameplayTagList=(Tag="Item.Utility",DevComment="")
+GameplayTagList=(Tag="Item.Weapon",DevComment="")
+GameplayTagList=(Tag="Reasource",DevComment="")
+GameplayTagList=(Tag="Reasource.ConductiveShreads",DevComment="")
+GameplayTagList=(Tag="Reasource.LiquidBondingAgent",DevComment="")
+GameplayTagList=(Tag="Reasource.ScrapMetal",DevComment="")

